version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    user: "1001"
    volumes:
      - ./data/ollama:/home/ollama/.ollama
    ports:
      - "11434:11434"
    # Uncomment the following section if GPU support is needed:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
